name: voice_alarm_m
description: A multi voice alarm app with recording and playback
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_sound:
    git:
      url: https://github.com/dooboolab/flutter_sound.git
      ref: master
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  android_alarm_manager_plus: ^5.0.0
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_sound_platform_interface: ^10.3.8
  flutter_sound_web: ^10.3.8

flutter:
  uses-material-design: true